/*
 * GENERATED BY http://quenchjs.com/
*/

const gulp = require('gulp'),
  plumber = require('gulp-plumber'),
  rename = require('gulp-rename');
const minifycss = require('gulp-minify-css');
const sass = require('gulp-sass');
const paths = {
  sass: {
    src: [
      './src/web/css/*.scss'
    ],
    dist: './src/web/css/'
  }
}
const eslint = require('gulp-eslint')

gulp.task('styles', function(done){
  gulp.src(paths.sass.src)
    .pipe(plumber({
      errorHandler: function (error) {
        console.log(error.message);
        this.emit('end');
    }}))
    .pipe(sass({
      errLogToConsole: true
    }))
    .pipe(rename({ extname: '.min.css' }))
    .pipe(minifycss())
    .pipe(gulp.dest(paths.sass.dist))
    .on('end', done);
});

gulp.task('lint', () => {
  return gulp.src(['src/**/*.js'])
    .pipe(eslint())
    .pipe(eslint.format())
    .pipe(eslint.failAfterError())
    .on('end', () => { process.exit() } )
});

gulp.task('watch', function() {
  gulp.watch(paths.sass.src, ['styles']);
});

gulp.task('default', ['styles', 'lint']);
gulp.run('watch');
